**/*.go {
  prep: go mod tidy
  prep: go test ./...
}

# Exclude all test files of the form *_test.go
**/*.go !**/*_test.go **/*.html assets/styles.css{
  prep: go build -o build/daemon ./cmd/server
  daemon +sigterm: ./build/daemon
}