name: Build

on:
  workflow_call:
    inputs:
      retiontion:
        default: 5
        description: Duration after which artifact will expire in days.
        required: false
        type: number

jobs:
  build:
    name: Build go app for ${{ vars.APP_NAME }}
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
      GOPRIVATE: github.com/crossroad-consulting/*
    if: github.event_name != 'pull_request' || (github.event.pull_request.draft == false && github.event.action != 'closed')
    steps:
      - uses: actions/checkout@v7

      - name: Tailwind
        run: docker compose run tailwind npx @tailwindcss/cli -i /app/src/styles.css -o /app/dst/styles.css --minify

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      
      - name: Format
        run: gofmt -s -w $(find . -type f -name '*.go' -not -path "./vendor/*")

      - name: Install dependencies
        run: go mod tidy
      
      - name: Test
        run: go test -v -cover ./...

      - name: Build
        run: go build -v --ldflags "-s -w" -o build/${{ vars.APP_NAME }} ./cmd/server

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ vars.APP_NAME }}
          path: build/${{ vars.APP_NAME }}
          retention-days: ${{ inputs.retiontion }}
